//! Phase 1B.1 pilot: specta/tauri-specta TypeScript binding emitter.
//!
//! Lives inside the lib crate (rather than the `gen-bindings` bin) so the
//! hidden macros generated by `#[specta::specta]` — which are only
//! reachable from within the defining crate — can be resolved by
//! `tauri_specta::collect_commands!`. The bin is a thin shim that calls
//! [`export`].
//!
//! This module is `#[doc(hidden)]` — it is not part of the library's
//! public API and may change without notice. Its only consumer is
//! `src/bin/gen-bindings.rs`.
//!
//! See `docs/specta-migration-guide.md` for the playbook to expand
//! coverage beyond the pilot allow-list.

use std::path::Path;

use specta_typescript::Typescript;
use tauri_specta::Builder;

use crate::error::ErrorCode;
use crate::types::IndexingProgressPayload;
use tracepilot_orchestrator::bridge::manager::BridgeMetricsSnapshot;
use tracepilot_orchestrator::context_capture::CaptureProgress;

const HEADER: &str = "\
// ──────────────────────────────────────────────────────────────────
// DO NOT EDIT — generated by `pnpm gen:bindings`
// (crates/tracepilot-tauri-bindings/src/bin/gen-bindings.rs).
//
// Regenerate after changing any Rust type with `specta::Type` in the
// pilot allow-list. CI fails if this file is stale.
// See docs/specta-migration-guide.md for the playbook.
// ──────────────────────────────────────────────────────────────────
";

/// Build the pilot `tauri_specta::Builder` and export it as TypeScript to
/// `out_path`. Called by the `gen-bindings` bin; see module docs.
pub fn export(out_path: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let builder = Builder::<tauri::Wry>::new()
        .commands(tauri_specta::collect_commands![
            crate::commands::sdk::sdk_bridge_metrics,
            crate::commands::session::list_sessions,
            crate::commands::session::check_session_freshness,
            crate::commands::session::get_session_background_tasks,
            // wave 98 — state/system commands
            crate::commands::state::get_db_size,
            crate::commands::state::get_session_count,
            crate::commands::state::is_session_running,
            crate::commands::state::get_install_type,
            crate::commands::state::check_for_updates,
            crate::commands::state::get_git_info,
            // wave 98 — config validation (co-located DTO with state types)
            crate::commands::config_cmds::validate_session_dir,
            crate::commands::config_sources::validate_claude_config_dir,
            crate::commands::source_diagnostics::get_source_format_diagnostics,
            // FU-14 — expanded specta coverage (primitives-only batch)
            crate::commands::config_cmds::check_config_exists,
            crate::commands::config_cmds::factory_reset,
            crate::commands::config_cmds::save_agent_definition,
            crate::commands::config_cmds::delete_session_template,
            crate::commands::config_cmds::restore_default_templates,
            crate::commands::config_cmds::increment_template_usage,
            crate::commands::logging::get_log_path,
            crate::commands::logging::export_logs,
            crate::commands::mcp::mcp_toggle_server,
            crate::commands::orchestration::is_git_repo,
        ])
        .typ::<ErrorCode>()
        .typ::<BridgeMetricsSnapshot>()
        .typ::<CaptureProgress>()
        .typ::<IndexingProgressPayload>();

    tracepilot_core::utils::fs::ensure_parent_dir(out_path)?;

    let exporter = Typescript::default().header(HEADER);
    builder.export(exporter, out_path)?;
    normalize_generated_whitespace(out_path)?;
    Ok(())
}

/// Shared wire DTOs live in the dependency-free types package, so consumers do
/// not acquire a runtime dependency on Tauri just to use a configuration type.
pub fn export_contracts(out_path: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let types = specta::Types::default()
        .register::<crate::config::TracePilotConfig>()
        .register::<crate::config::TracePilotConfigPatch>()
        .register::<CaptureProgress>();
    // Optional fields have different serialize/deserialize shapes (TOML
    // defaults and omitted prices), so retain both directions explicitly.
    let resolved = specta_serde::apply_phases(types)?;
    tracepilot_core::utils::fs::ensure_parent_dir(out_path)?;
    Typescript::default()
        .header(HEADER)
        .export_to(out_path, &resolved)?;
    normalize_generated_whitespace(out_path)?;
    Ok(())
}

fn normalize_generated_whitespace(out_path: &Path) -> Result<(), std::io::Error> {
    // Specta preserves blank doc lines and multiline intersections' spaces;
    // keep generated artifacts
    // whitespace-clean while preserving deterministic output across platforms.
    let generated = std::fs::read_to_string(out_path)?;
    let mut normalized = generated
        .lines()
        .map(str::trim_end)
        .collect::<Vec<_>>()
        .join("\n");
    normalized.push('\n');
    std::fs::write(out_path, normalized)?;
    Ok(())
}
