/** Offline, focused iteration gallery. Not included in published CI artifacts. */
import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";

export async function writeLocalGallery(output, reports, viewport) {
  const data = JSON.stringify(reports).replaceAll("<", "\\u003c");
  await writeFile(
    resolve(output, "index.html"),
    `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" href="data:,"><title>TracePilot fixture review</title>
<style>body{margin:0;background:#101014;color:#eee;font:14px system-ui;display:grid;grid-template-columns:270px 1fr;height:100vh}aside{overflow:auto;border-right:1px solid #383840;padding:16px}h1{font-size:18px}input{box-sizing:border-box;width:100%;padding:9px;background:#25252b;color:inherit;border:1px solid #555;border-radius:5px}button{display:block;width:100%;background:transparent;color:inherit;border:0;text-align:left;padding:10px;cursor:pointer;border-radius:5px}button[aria-current=true]{background:#423477}small{display:block;color:#aaa;margin-top:3px}main{min-width:0;overflow:auto}header{padding:16px;position:sticky;top:0;background:#101014;border-bottom:1px solid #383840}img{display:block;width:100%;height:auto}pre{white-space:pre-wrap;color:#f99}a{color:#bfaaff}</style>
<aside><h1>TracePilot fixture review</h1><p>${viewport.width} × ${viewport.height} · synthetic frontend</p><input type="search" aria-label="Filter cases" placeholder="Filter tool or state"><nav aria-label="Fixture cases"></nav></aside><main><header><strong id="title"></strong><small id="state"></small><a id="original">Open full-size image</a><pre id="errors"></pre></header><img id="screenshot" alt=""></main>
<script>const cases=${data};const nav=document.querySelector('nav');const filter=document.querySelector('input');function select(item){if(!item){document.querySelector('#title').textContent='No captures available';return;}document.querySelector('#title').textContent=item.id+' · '+item.status;document.querySelector('#state').textContent=item.state;document.querySelector('#errors').textContent=item.errors.join('\\n');const image=document.querySelector('#screenshot');image.src=item.id+'.png';image.alt=item.state;document.querySelector('#original').href=image.src;location.hash=item.id;nav.querySelectorAll('button').forEach(b=>b.setAttribute('aria-current',b.dataset.id===item.id));}function render(){nav.replaceChildren();for(const item of cases.filter(c=>(c.id+' '+c.state).toLowerCase().includes(filter.value.toLowerCase()))){const b=document.createElement('button');b.dataset.id=item.id;b.setAttribute('aria-current',item.id===location.hash.slice(1));b.textContent=item.id;const s=document.createElement('small');s.textContent=item.status;b.append(s);b.onclick=()=>select(item);nav.append(b);} }filter.oninput=render;window.onhashchange=()=>select(cases.find(c=>c.id===location.hash.slice(1))||cases[0]);render();select(cases.find(c=>c.id===location.hash.slice(1))||cases[0]);</script></html>`,
  );
}
