export const hydratedBridgeState = {
  status: {
    state: "connected",
    sdkAvailable: true,
    enabledByPreference: true,
    cliVersion: "1.0.0",
    protocolVersion: 1,
    activeSessions: 1,
    error: null,
    connectionMode: "stdio",
  },
  sessions: [
    { sessionId: "tracked-1", isActive: true },
    { sessionId: "tracked-2", isActive: false },
  ],
  metrics: { eventsForwarded: 2, eventsDroppedDueToLag: 0, lagOccurrences: 0 },
  sessionStates: [
    {
      sessionId: "tracked-1",
      status: "idle",
      currentTurnId: null,
      assistantText: "ready",
      reasoningText: "",
      tools: [],
      usage: null,
      pendingPermission: null,
      pendingUserInput: null,
      lastEventId: null,
      lastEventType: null,
      lastEventTimestamp: null,
      lastError: null,
      reducerWarnings: [],
    },
  ],
};
