//! Session file browser Tauri commands.
//!
//! Provides read-only, sandboxed access to files within a session's
//! directory. All paths are validated and canonicalized to prevent
//! traversal attacks.

mod commands;
mod image_preview;
mod search;
mod security;
mod types;

#[cfg(test)]
#[path = "security_revalidate_tests.rs"]
mod security_revalidate_tests;

// Glob re-exports are required so `tauri::generate_handler!` can resolve the
// hidden `__cmd__*` items generated by `#[tauri::command]`.
pub use commands::*;
pub use image_preview::*;
pub use search::*;
