import {
  ArrowDown,
  ArrowUp,
  BarChart3,
  Bookmark,
  BookOpen,
  Bot,
  Brain,
  Bug,
  Circle,
  CircleAlert,
  ClipboardList,
  Cloud,
  Code,
  Compass,
  Cpu,
  Database,
  Download,
  Eye,
  FilePenLine,
  FilePlus,
  FileText,
  Flag,
  FlaskConical,
  Folder,
  FolderOpen,
  FolderSearch,
  GitBranch,
  GitCommit,
  GitPullRequest,
  Globe,
  Hammer,
  Info,
  Key,
  Layers,
  Lightbulb,
  Lock,
  type LucideIcon,
  MessageCircle,
  Microscope,
  Minus,
  Package,
  Pencil,
  Play,
  Plug,
  Puzzle,
  RefreshCw,
  Rocket,
  RotateCcw,
  ScanEye,
  Search,
  Send,
  Server,
  Settings,
  Share2,
  Shield,
  Sparkles,
  SquareStack,
  Target,
  Terminal,
  TestTube,
  Trash2,
  TriangleAlert,
  Upload,
  Workflow,
  Wrench,
  Zap,
} from "lucide-vue-next";
import type { LucideName } from "./templateCatalogue";

export type LucideComponent = LucideIcon;

export const LUCIDE_ICON_COMPONENTS = {
  "arrow-down": ArrowDown,
  "arrow-up": ArrowUp,
  "bar-chart-3": BarChart3,
  bookmark: Bookmark,
  "book-open": BookOpen,
  bot: Bot,
  brain: Brain,
  bug: Bug,
  circle: Circle,
  "circle-alert": CircleAlert,
  "clipboard-list": ClipboardList,
  cloud: Cloud,
  code: Code,
  compass: Compass,
  cpu: Cpu,
  database: Database,
  download: Download,
  eye: Eye,
  "file-pen-line": FilePenLine,
  "file-plus": FilePlus,
  "file-text": FileText,
  flag: Flag,
  "flask-conical": FlaskConical,
  folder: Folder,
  "folder-open": FolderOpen,
  "folder-search": FolderSearch,
  "git-branch": GitBranch,
  "git-commit": GitCommit,
  "git-pull-request": GitPullRequest,
  globe: Globe,
  hammer: Hammer,
  info: Info,
  key: Key,
  layers: Layers,
  lightbulb: Lightbulb,
  lock: Lock,
  "message-circle": MessageCircle,
  microscope: Microscope,
  minus: Minus,
  package: Package,
  pencil: Pencil,
  play: Play,
  plug: Plug,
  puzzle: Puzzle,
  "refresh-cw": RefreshCw,
  rocket: Rocket,
  "rotate-ccw": RotateCcw,
  "scan-eye": ScanEye,
  search: Search,
  send: Send,
  server: Server,
  settings: Settings,
  "share-2": Share2,
  shield: Shield,
  sparkles: Sparkles,
  "square-stack": SquareStack,
  target: Target,
  terminal: Terminal,
  "test-tube": TestTube,
  "trash-2": Trash2,
  "triangle-alert": TriangleAlert,
  upload: Upload,
  workflow: Workflow,
  wrench: Wrench,
  zap: Zap,
} satisfies Record<LucideName, LucideIcon>;

const LUCIDE_ICON_LOOKUP: Record<string, LucideIcon> = LUCIDE_ICON_COMPONENTS;

export function resolveLucideIcon(
  name: string | null | undefined,
  fallback: LucideIcon | null = Wrench,
): LucideIcon | null {
  if (!name) return fallback;
  return LUCIDE_ICON_LOOKUP[name] ?? fallback;
}
