// Curated 50-glyph dev-tool subset for <LucideIconPicker>.
// See design-system/pages/19-session-launcher.md §LucideIconPicker (Catalogue).
// Keep names in kebab-case (lucide canonical). Adding entries is a deliberate
// design change reviewed alongside token additions.

export type LucideName = string;

export const TEMPLATE_ICON_CATALOGUE: ReadonlyArray<LucideName> = Object.freeze([
  "rocket",
  "bot",
  "compass",
  "brain",
  "scan-eye",
  "wrench",
  "bug",
  "git-branch",
  "git-pull-request",
  "git-commit",
  "terminal",
  "code",
  "file-text",
  "folder",
  "folder-open",
  "database",
  "cloud",
  "zap",
  "target",
  "flag",
  "bookmark",
  "book-open",
  "flask-conical",
  "hammer",
  "package",
  "play",
  "refresh-cw",
  "search",
  "settings",
  "shield",
  "sparkles",
  "square-stack",
  "test-tube",
  "triangle-alert",
  "workflow",
  "bar-chart-3",
  "lightbulb",
  "eye",
  "lock",
  "key",
  "globe",
  "server",
  "cpu",
  "layers",
  "puzzle",
  "plug",
  "send",
  "share-2",
  "upload",
  "download",
]);
