#!/usr/bin/env python3
"""Regenerate the route catalogue and storyboard from the production Vue router.

The router remains the source of truth. CI compares its SHA-256 with the generated
catalogue, so route additions/removals cannot silently drift away from visual tests.
"""
from __future__ import annotations
import hashlib, json, re, sys
from pathlib import Path

ROOT=Path(__file__).resolve().parents[2]
MANIFEST=ROOT/'tests/visual-regression/routes.json'
existing=json.loads(MANIFEST.read_text('utf-8')) if MANIFEST.exists() else {}
router=ROOT/existing.get('generated_from','') if existing else None
if not router or not router.exists():
    candidates=[]
    for p in ROOT.rglob('*.ts'):
        if any(x in p.parts for x in ('.git','node_modules','target','dist')): continue
        text=p.read_text('utf-8',errors='ignore')
        if 'createRouter' in text: candidates.append((text.count('path:'),p,text))
    if not candidates: raise SystemExit('Unable to find the production Vue router')
    _,router,text=max(candidates,key=lambda x:x[0])
else:
    text=router.read_text('utf-8')

def object_span(text,pos):
    stack=[]; pairs=[]; quote=None; esc=False; line=False; block=False; i=0
    while i<len(text):
        c=text[i]; n=text[i+1] if i+1<len(text) else ''
        if line:
            if c=='\n': line=False
            i+=1; continue
        if block:
            if c=='*' and n=='/': block=False; i+=2; continue
            i+=1; continue
        if quote:
            if esc: esc=False
            elif c=='\\': esc=True
            elif c==quote: quote=None
            i+=1; continue
        if c=='/' and n=='/': line=True; i+=2; continue
        if c=='/' and n=='*': block=True; i+=2; continue
        if c in "'\"`": quote=c; i+=1; continue
        if c=='{': stack.append(i)
        elif c=='}' and stack: pairs.append((stack.pop(),i+1))
        i+=1
    spans=[s for s in pairs if s[0]<=pos<s[1]]
    return min(spans,key=lambda s:s[1]-s[0]) if spans else None

routes=[]; seen=set()
for m in re.finditer(r"\bpath\s*:\s*(['\"`])([^'\"`]+)\1",text):
    path=m.group(2)
    if not path.startswith('/') or 'pathMatch' in path: continue
    span=object_span(text,m.start())
    if not span: continue
    obj=text[span[0]:span[1]]
    if re.search(r'\bredirect\s*:',obj): continue
    nm=re.search(r"\bname\s*:\s*(['\"`])([^'\"`]+)\1",obj)
    tm=re.search(r"\btitle\s*:\s*(['\"`])([^'\"`]+)\1",obj)
    im=re.search(r"\bcomponent\s*:\s*(?:\(\)\s*=>\s*)?import\(\s*(['\"])([^'\"]+)\1\s*\)",obj)
    cm=re.search(r"\bcomponent\s*:\s*([A-Za-z_$][\w$]*)",obj)
    name=nm.group(2) if nm else None
    key=(path,name)
    if key in seen: continue
    seen.add(key)
    slug=re.sub(r'[^a-z0-9]+','-',(name or path.strip('/') or 'home').lower()).strip('-') or 'home'
    routes.append({'path':path,'name':name or slug,'id':slug,
      'title':(tm.group(2) if tm else re.sub(r'[-_]+',' ',name or slug).title()),
      'component':im.group(2) if im else (cm.group(1) if cm else None)})
routes.sort(key=lambda r:(r['path'].count('/'),r['path']))
manifest={'schema_version':1,'generated_from':router.relative_to(ROOT).as_posix(),
  'source_sha256':hashlib.sha256(router.read_bytes()).hexdigest(),
  'route_count':len(routes),'routes':routes}
MANIFEST.parent.mkdir(parents=True,exist_ok=True)
MANIFEST.write_text(json.dumps(manifest,indent=2)+'\n','utf-8')
lines=['# TracePilot application storyboard','',
  '> Generated from the production router. Run `pnpm routes:generate` after route changes.','',
  f'**{len(routes)} routed views** are included in route-level smoke and visual review.','',
  '| View | Route | Stable identity | Component | Review states |','|---|---|---|---|---|']
for r in routes:
    comp=f'`{r["component"]}`' if r['component'] else 'Resolved by router'
    lines.append(f'| {r["title"]} | `{r["path"]}` | `{r["id"]}` | {comp} | default, loading, empty, populated, error, keyboard, narrow |')
lines += ['', '## Global surfaces','',
  'The route captures are supplemented by interaction tests for the application shell, navigation, search/command palette, dialogs, drawers, toasts, context menus, import/export progress, and error recovery.', '',
  '## Capture provenance','',
  'Images under `artifacts/visual-regression` are generated by Playwright from a running Vite build with deterministic Tauri IPC mocks. Repository documentation images are never used as capture fallbacks. A failed browser launch or route render fails the capture command instead of substituting an existing asset.','']
(ROOT/'docs/quality').mkdir(parents=True,exist_ok=True)
(ROOT/'docs/quality/application-storyboard.md').write_text('\n'.join(lines)+'\n','utf-8')
print(f'Generated {len(routes)} routes from {router.relative_to(ROOT)}')
