/** Central list of Tauri IPC command names used by the client wrapper. */
export const IPC_COMMANDS = [
  // Session and search
  "list_sessions",
  "get_session_detail",
  "get_session_incidents",
  "get_session_turns",
  "check_session_freshness",
  "get_session_events",
  "get_session_todos",
  "get_session_checkpoints",
  "get_session_plan",
  "get_shutdown_metrics",
  "search_sessions",
  "search_content",
  "get_search_facets",
  "get_search_stats",
  "get_search_repositories",
  "get_search_tool_names",
  "rebuild_search_index",
  "fts_health",
  "fts_integrity_check",
  "fts_optimize",
  "get_result_context",
  // Analytics + indexing
  "reindex_sessions",
  "reindex_sessions_full",
  "get_analytics",
  "get_tool_analysis",
  "get_code_impact",
  // Config + system info
  "check_config_exists",
  "get_config",
  "save_config",
  "validate_session_dir",
  "get_db_size",
  "get_session_count",
  "is_session_running",
  "factory_reset",
  "get_tool_result",
  "resume_session_in_terminal",
  "check_for_updates",
  "get_install_type",
  "get_git_info",
  // Orchestration: system deps + worktrees
  "check_system_deps",
  "list_worktrees",
  "create_worktree",
  "remove_worktree",
  "prune_worktrees",
  "list_branches",
  "get_worktree_disk_usage",
  "is_git_repo",
  "lock_worktree",
  "unlock_worktree",
  "get_worktree_details",
  "get_default_branch",
  "fetch_remote",
  "list_registered_repos",
  "add_registered_repo",
  "remove_registered_repo",
  "toggle_repo_favourite",
  "discover_repos_from_sessions",
  // Orchestration: launcher + config injector
  "launch_session",
  "get_available_models",
  "open_in_explorer",
  "open_in_terminal",
  "get_agent_definitions",
  "save_agent_definition",
  "get_copilot_config",
  "save_copilot_config",
  "create_config_backup",
  "list_config_backups",
  "restore_config_backup",
  "delete_config_backup",
  "preview_backup_restore",
  "diff_config_files",
  // Orchestration: version manager + templates
  "discover_copilot_versions",
  "get_active_copilot_version",
  "get_migration_diffs",
  "migrate_agent_definition",
  "list_session_templates",
  "save_session_template",
  "delete_session_template",
  "restore_default_templates",
  "increment_template_usage",
  // Logging
  "get_log_path",
  "export_logs",
  // Export / Import
  "export_sessions",
  "preview_export",
  "get_session_sections",
  "preview_import",
  "import_sessions",
  "export_session_folder_zip",
  // MCP commands
  "mcp_list_servers",
  "mcp_get_server",
  "mcp_add_server",
  "mcp_update_server",
  "mcp_remove_server",
  "mcp_toggle_server",
  "mcp_check_health",
  "mcp_check_server_health",
  "mcp_import_from_file",
  "mcp_import_from_github",
  "mcp_compute_diff",
  // Skills commands
  "skills_list_all",
  "skills_get_skill",
  "skills_create",
  "skills_update",
  "skills_update_raw",
  "skills_delete",
  "skills_rename",
  "skills_duplicate",
  "skills_list_assets",
  "skills_add_asset",
  "skills_copy_asset_from",
  "skills_remove_asset",
  "skills_read_asset",
  "skills_import_local",
  "skills_import_file",
  "skills_import_github",
  "skills_discover_github",
  "skills_import_github_skill",
  "skills_gh_auth_status",
  "skills_discover_local",
  "skills_discover_repos",
  // AI Task System
  "task_create",
  "task_create_batch",
  "task_get",
  "task_list",
  "task_cancel",
  "task_retry",
  "task_delete",
  "task_stats",
  "task_list_jobs",
  "task_cancel_job",
  "task_list_presets",
  "task_get_preset",
  "task_save_preset",
  "task_delete_preset",
  "task_orchestrator_health",
  "task_orchestrator_start",
  "task_orchestrator_stop",
  "task_ingest_results",
  "task_attribution",
  // SDK bridge commands
  "sdk_connect",
  "sdk_disconnect",
  "sdk_status",
  "sdk_cli_status",
  "sdk_create_session",
  "sdk_resume_session",
  "sdk_send_message",
  "sdk_abort_session",
  "sdk_destroy_session",
  "sdk_unlink_session",
  "sdk_set_session_mode",
  "sdk_set_session_model",
  "sdk_list_sessions",
  "sdk_get_quota",
  "sdk_get_auth_status",
  "sdk_list_models",
  "sdk_get_foreground_session",
  "sdk_set_foreground_session",
  "sdk_detect_ui_server",
  "sdk_launch_ui_server",
  "sdk_bridge_metrics",
  "sdk_answer_user_input",
  // Window management
  "open_session_window",
  "close_session_window",
] as const;

export type CommandName = (typeof IPC_COMMANDS)[number];
