/**
 * Barrel entry point for `@tracepilot/client`.
 *
 * Domain modules live alongside this file; see Wave 45 of
 * `docs/tech-debt-plan-revised-2026-04.md` §5.1 for the split.
 * Public API is preserved byte-for-byte — every symbol below must
 * remain importable by consumers with its original name and type.
 */

export * from "./analytics.js";
export { type CommandName, IPC_COMMANDS } from "./commands.js";
export * from "./config.js";
export { IPC_EVENTS, type IpcEventName } from "./events.js";
export * from "./export.js";
// Re-export DTOs generated by tauri-specta (wave 98). These replace
// hand-written mirrors that previously lived in `@tracepilot/types`.
// Consumers should import them from `@tracepilot/client` alongside the
// IPC wrappers that return them.
export type {
  BindingsErrorIpc,
  ErrorCode,
  GitInfo,
  UpdateCheckResult,
  ValidateSessionDirResult,
} from "./generated/bindings.js";
export type { InvokeFn, InvokeOptions, IpcPerfHook } from "./invoke.js";
// IPC performance instrumentation utilities
export {
  clearIpcPerfLog,
  disablePerfTracing,
  enablePerfTracing,
  getIpcPerfLog,
  isTauri,
} from "./invoke.js";
export * from "./maint.js";

export * from "./mcp.js";
export * from "./orchestration.js";
export * from "./sdk.js";
export * from "./search.js";
export * from "./sessions.js";
export * from "./skills.js";
