/**
 * Public IPC names and DTOs. SDK types share the definitions returned by
 * the client wrappers; runtime wire-format ownership remains in Rust.
 */

// Preserve existing client imports without maintaining a second SDK schema.
export type {
  BridgeAuthStatus,
  BridgeConnectConfig,
  BridgeConnectionState,
  BridgeEvent,
  BridgeHydrationSnapshot,
  BridgeMessagePayload,
  BridgeMetricsSnapshot,
  BridgeModelInfo,
  BridgeQuota,
  BridgeQuotaSnapshot,
  BridgeSessionConfig,
  BridgeSessionInfo,
  BridgeSessionMode,
  BridgeStatus,
  DetectedUiServer,
  PendingRequestSummary,
  SessionLiveState,
  SessionRuntimeStatus,
  ToolProgressSummary,
} from "@tracepilot/types";
export { type CommandName, IPC_COMMANDS } from "./commands.js";
export { IPC_EVENTS, type IpcEventName } from "./events.js";
// Transport DTOs generated by tauri-specta.
export type {
  BackgroundTask,
  BackgroundTaskKind,
  BackgroundTaskStatus,
  BindingsErrorIpc,
  ErrorCode,
  FormatNameCountDto,
  GitInfo,
  SourceFormatDiagnostics,
  UpdateCheckResult,
  ValidateSessionDirResult,
} from "./generated/bindings.js";
