//! Search and indexing Tauri commands.
//!
//! Split into focused submodules while preserving the public
//! `commands::search::<command_name>` paths used by Tauri registration.
//!
//! Glob re-exports are required so `tauri::generate_handler!` can resolve the
//! hidden `__cmd__*` items generated by `#[tauri::command]`.

mod cache;
mod content;
mod maintenance;
mod references;
mod reindex;
mod reindex_lifecycle;
mod sessions;

#[cfg(test)]
pub(crate) use cache::index_read_cache_invalidations;
pub use cache::invalidate_index_read_caches;
pub use content::*;
pub use maintenance::*;
pub use references::*;
pub use reindex::*;
pub use sessions::*;
