//! Search and indexing Tauri commands.
//!
//! Split into focused submodules while preserving the public
//! `commands::search::<command_name>` paths used by Tauri registration.
//!
//! Glob re-exports are required so `tauri::generate_handler!` can resolve the
//! hidden `__cmd__*` items generated by `#[tauri::command]`.

mod cache;
mod content;
mod maintenance;
mod references;
mod reindex;
mod sessions;

#[allow(unused_imports)]
pub use cache::invalidate_facets_cache;
pub use content::*;
pub use maintenance::*;
pub use references::*;
pub use reindex::*;
pub use sessions::*;
