//! Tauri IPC commands for the AI agent task system.
//!
//! Commands for task CRUD, orchestrator lifecycle, health monitoring,
//! and result ingestion.
//!
//! Split by domain into submodules; re-exported via `pub use` so that
//! `tauri::generate_handler!` can resolve the hidden `__cmd__*` items
//! generated by `#[tauri::command]` via the `commands::tasks::*` path.

mod crud;
mod ingest;
mod jobs;
mod orchestrator;
mod orchestrator_start;
mod presets;

pub use crud::*;
pub use ingest::*;
pub use jobs::*;
pub use orchestrator::*;
pub use orchestrator_start::*;
pub use presets::*;

// ─── Shared helpers ─────────────────────────────────────────────────

/// Resolve the effective model for a task by checking the preset's
/// `model_override` first, falling back to `default_model`.
///
/// This centralises the model-resolution pattern used whenever a task
/// needs to be hot-added or retried into a running orchestrator manifest.
pub(crate) fn resolve_task_model(
    presets_dir: &std::path::Path,
    preset_id: &tracepilot_core::ids::PresetId,
    default_model: &str,
) -> String {
    tracepilot_orchestrator::presets::io::get_preset(presets_dir, preset_id)
        .ok()
        .and_then(|p| p.execution.model_override.clone())
        .unwrap_or_else(|| default_model.to_string())
}

/// Build minimal context when preset loading or full assembly fails.
pub(crate) fn fallback_context(
    task: &tracepilot_orchestrator::task_db::Task,
    result_path: &str,
) -> String {
    format!(
        "# Task: {}\n\n**Type:** {}\n**Preset:** {}\n\n\
         ## Input Parameters\n\n```json\n{}\n```\n\n\
         ## Output Format\n\nWrite your result as valid JSON to: `{}`\n\
         Use atomic write: write to `.tmp` then rename.\n",
        task.id,
        task.task_type,
        task.preset_id,
        serde_json::to_string_pretty(&task.input_params).unwrap_or_default(),
        result_path,
    )
}
